cmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from index.views import index, login_view, logout, error
from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index),
    url(r'^index/$', index),
    url(r'^index.html$', index),
    url(r'^jigui/', include('jigui.urls')),
    url(r'^login.html$', login_view),
    url(r'^login/$', login_view),
    url(r'^logout.html$', logout),
    url(r'^error.html$', error),
    url(r'^host/', include('hostinfo.urls')),
]

jigui/models.py
from django.db import models


class JiguiInfo(models.Model):
    #jifang_group = models.ForeignKey("index.JifangGroup", to_field='uid',default=1)  ##用户组表,默认id  user_group_id 数字
    name = models.CharField(max_length=64, verbose_name='名字')
    jq = models.CharField(max_length=64,verbose_name='总数')
    zy = models.CharField(max_length=64,verbose_name='自用',null=True)
    ziy = models.CharField(max_length=64,verbose_name='在用',null=True)
    zs = models.CharField(max_length=64,verbose_name='自用',null=True)
    zb = models.CharField(max_length=64,verbose_name='在售',null=True)
    sh = models.CharField(max_length=64,verbose_name='整包',null=True)
    xz = models.CharField(max_length=64,verbose_name='闲置',null=True)

    d = models.ManyToManyField(to="dx",verbose_name='多选')
    yong = models.BooleanField(verbose_name='是否在用')

    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间')
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间')

    class  Meta:
        db_table ="JiguiInfo"
        verbose_name="机柜"
        verbose_name_plural = '机柜中心'


    def __str__(self):
        return self.name


class  dx(models.Model):
    xuan = models.CharField(max_length=64,verbose_name='多选选项')

    class  Meta:
        db_table ="dx"
        verbose_name="多选"
        verbose_name_plural = '多选'
    def __str__(self):
        return self.xuan






templates/base.html
{% load cache %}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>首页</title>


    {% include 'link_css.html' %}
    {% block header-css %}
    {% endblock %}

</head>

<body>

<div id="wrapper">

    {% cache  1    nav  %}
    {% include 'nav.html' %}
    {% endcache%}


    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            {% include 'navbar-static-top.html' %}
        </div>


      <div class="row wrapper border-bottom white-bg page-heading">
            <div class="col-lg-10">
                <h2>{% block page-content-title %}  {% endblock %}</h2>



                    {% block page-nav-tab %}

                {% endblock %}

            </div>
            <div class="col-lg-2">

            </div>
        </div>


        {% block page-content %}


        {% endblock %}

        {% include 'footer.html' %}
    </div>

</div>

</body>


</html>
{#    <script>#}
{##}
{##}
{#         var test = window.location.pathname;#}
{#         alert(test);#}
{#         var b = '/host/host.html';#}
{#         if (test == b) {#}
{#             var div = document.getElementById('host_xiangxi');#}
{#             div.setAttribute("class", "active");#}
{#         }#}
{##}
{##}
{#</script>#}
 {% include 'foot_script.html' %}
 {% block  js %} {% endblock %}

templates/error.html
{% extends "base.html" %}


    {% block header-css %}
    {% endblock %}




{% block page-content %}
 <div class="row  border-bottom white-bg dashboard-header">

                    <div class="col-sm-3">
                        <h2>欢迎您，{{ request.session.user }} </h2>
                        <small>没有权限</small>

                    </div>


            </div>

{% endblock %}

templates/foot_script.html
<!-- Mainly scripts -->
<script src="/static/js/jquery-2.1.1.js"></script>
<script src="/static/js/bootstrap.min.js"></script>


<script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="/static/js/plugins/jeditable/jquery.jeditable.js"></script>
<!-- Custom and plugin javascript -->
<script src="/static/js/inspinia.js"></script>
<script src="/static/js/plugins/pace/pace.min.js"></script>
<script src="/static/js/plugins/dataTables/datatables.min.js"></script>

<!-- iCheck -->
<script src="/static/js/plugins/iCheck/icheck.min.js"></script>


<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#gaoji").hide();
        $("#ji").click(function () {
            $("#jiben").show();
            $("#gaoji").hide();
        });
        $("#gao").click(function () {
            $("#jiben").hide();
            $("#gaoji").show();
        });
    });
</script>
<script>
    $(document).ready(function () {
        $("#toubu").click(function () {
            $("body").toggleClass("mini-navbar");
            SmoothlyMenu();
        });
    });
</script>
<script>
    $(document).ready(function () {
        $(".collapse-links").click(function () {
            var ibox = $(this).closest('div.ibox');
            var button = $(this).find('i');
            var content = ibox.find('div.ibox-content');
            content.slideToggle(200);
            button.toggleClass('fa-chevron-up').toggleClass('fa-chevron-down');
            ibox.toggleClass('').toggleClass('border-bottom');
            setTimeout(function () {
                ibox.resize();
                ibox.find('[id^=map-]').resize();
            }, 50);
        });
    });
</script>


<script>





    $(document).ready(function () {
        $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[ 1, 'asc' ]],
         　　         　　columnDefs:[{
    　　　　'targets' : [0],    //除第六，第七两列外，都默认不排序
    　　　　'orderable' : false
    　           　}],


            dom: '<"html5buttons"B>lTfgitp',
            buttons: [
                {extend: 'copy'},
                {extend: 'csv'},
                {extend: 'excel', title: 'ExampleFile'},
                {extend: 'pdf', title: 'ExampleFile'},

                {
                    extend: 'print',
                    customize: function (win) {
                        $(win.document.body).addClass('white-bg');
                        $(win.document.body).css('font-size', '10px');

                        $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                    }
                }
            ]

        });

    });


</script>


<script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>


<script>

    $("#CheckedAll").click(function () {
                if ($(this).is(":checked")) {
                    $("[name=id]:checkbox").prop("checked", true);
                } else {
                    $("[name=id]:checkbox").prop("checked", false);
                }
            });


    $(function () {
        $('#cmd').click(function () {
            $.ajax({
                url: "/host/cmd.html",
                type: 'POST',
                data: $('#cmd_from').serialize(),
                success: function (data) {
                    var obj = JSON.parse(data);
                    {#                  var  obj1 = obj.data.replace(/\n/g,"<br>");#}
                    $('#ret').text(obj.data)

                }

            })
        })


        $('#yml').click(function () {
            $.ajax({
                url: "/host/yml.html",
                type: 'POST',
                data: $('#yml_from').serialize(),
                success: function (data) {
                    var obj = JSON.parse(data);
                    {#                  var  obj1 = obj.data.replace(/\n/g,"<br>");#}
                    $('#yml_result').text(obj.data)

                }

            })
        })


    });

    function clearBody() {
        location.reload()
    }

</script>


templates/footer.html
<div class="footer">
            <div class="pull-right">
               <strong></strong>
            </div>
            <div>
                <strong></strong> 设为首页 &copy; 2017
            </div>
        </div>

templates/index.html
{% extends "base.html" %}

    {% block header-css %}
    {% endblock %}




{% block page-content-title %} 首页 {% endblock %}

{% block page-nav-tab %}
 <ol class="breadcrumb">
                    <li>
                        <a href="../index.html">首页</a>
                    </li>
                    <li>
                        <a>详情</a>
                    </li>
                    <li class="active">
                        <strong>首页</strong></li>
</ol>
{% endblock %}



{% block page-content %}
  <div class="wrapper wrapper-content animated fadeInRight">

 <div class="row  border-bottom white-bg dashboard-header">

                    <div class="col-sm-3">
                        <h2>欢迎您，{{ user }} </h2>
                        <small>您有 42 条未读消息 和 6 条通知.</small>
                        <ul class="list-group clear-list m-t">
                            <li class="list-group-item fist-item">
                                <span class="pull-right">
                                    09:00 pm
                                </span>
                                <span class="label label-success">1</span> 请联系我
                            </li>
                            <li class="list-group-item">
                                <span class="pull-right">
                                    10:16 am
                                </span>
                                <span class="label label-info">2</span> 登记信息
                            </li>
                            <li class="list-group-item">
                                <span class="pull-right">
                                    08:22 pm
                                </span>
                                <span class="label label-primary">3</span> 开新店
                            </li>
                            <li class="list-group-item">
                                <span class="pull-right">
                                    11:06 pm
                                </span>
                                <span class="label label-default">4</span> 请回电话
                            </li>
                            <li class="list-group-item">
                                <span class="pull-right">
                                    12:00 am
                                </span>
                                <span class="label label-primary">5</span> 发邮件
                            </li>
                        </ul>
                    </div>


            </div>
     </div>
{% endblock %}

templates/link_css.html
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

<!-- Toastr style -->
<link href="/static/css/plugins/toastr/toastr.min.css" rel="stylesheet">

<!-- Gritter -->
<link href="/static/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">
<link href="/static/css/plugins/dataTables/datatables.min.css" rel="stylesheet">

<link href="/static/css/animate.css" rel="stylesheet">
<link href="/static/css/style.css" rel="stylesheet">

<link href="/static/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">


templates/login.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>登录</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

{#                <h1 class="logo-name">X</h1>#}

            </div>
            <h3>欢迎进入</h3>
            <p>CMDB
                <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
            </p>
            <p>登录进去。在行动中看到它。</p>
            <form class="m-t" role="form" action="login.html"  method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text"   name="user" class="form-control" placeholder="用户名" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="密码" required="">
                </div>


                <button type="submit" class="btn btn-primary block full-width m-b">登录</button>


                <a href="#">
                    <span style="color: red;"> {{ error_msg }}</span><br>
                    <small>忘记密码?</small></a>
                <p class="text-muted text-center"><small>没有账户?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="#">创建账户</a>
            </form>
            <p class="m-t"> <small>系统支持组 &copy; 2017</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="/static/js/jquery-2.1.1.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>

</body>

</html>

templates/nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" src="/static/img/profile_small.jpg"/>
                             </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>
                             </span> <span class="text-muted text-xs block"> {% ifequal  user.is_superuser  1 %}
                                管理员 {% else %} 普通用户 {% endifequal %}  <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">个人信息</a></li>
                        <li><a href="#">联系方式</a></li>
                        <li><a href="#">邮箱</a></li>
                        <li class="divider"></li>
                        <li><a href="/logout.html">退出登录</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    cmdbx
                </div>
            </li>
            <li class="active">
                <a href="#"><i class="fa fa-th-large"></i> <span class="nav-label">机柜</span> <span
                        class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="active">
                        <a href="{%   url    'jigui'   %}">详情</a></li>
{#                        {% if     perms.jigui.add_jiguiinfo %}#}
{#                        <li><a href="{%   url    'addx'   %}">添加</a></li>#}
{#                        {% endif %}#}
                    <li><a href="{%   url    'show'   %}">展示</a></li>
                </ul>
            </li>
            <li   class="active" >
                <a href="#"><i class="fa fa-laptop"></i> <span class="nav-label">主机</span> <span
                        class="fa arrow"></span></a>
                <ul class="nav nav-second-level" >
                    <li  ><a href="{% url   'host' %}">详情</a></li>
                    <li><a href="{% url   'yml' %}">yml</a></li>
                    <li><a href="{% url   'cmd' %}">命令行</a></li>
                    <li><a href="{% url   'history' %}">历史操作</a></li>
                </ul>
            </li>


        </ul>

    </div>
</nav>


templates/navbar-static-top.html


<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <a class=" minimalize-styl-2   btn btn-primary " href="#" id="toubu"><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <span class="m-r-sm text-muted welcome-message">欢迎  {{ user }}来到 CMDB系统</span>
        </li>

        <li>
            <a href="/logout.html">
                <i class="fa fa-sign-out"></i>退出登录
            </a>

        </li>
    </ul>
</nav>